### PR TITLE
Add provider for France

### LINKED ISSUE #6: French data
@maiste suggested looking at https://data.rte-france.com/ for data from France.

### PR DESCRIPTION
**Pull request by emillon**
This is based on the `eco2mix-national-tr` dataset.

Fixes #6

### CODE REVIEW

**Comment by emillon** [comment]
I'm not sure how it should be integrated with the rest of the repo; for now `dune exec ./example/main.exe` works.

**Comment by patricoferris** [comment]
Thanks, this looks great. Do you want to update the README too ? :))

**Comment by avsm** [comment]
Nice one! I _think_ this will be helpful to measuring the Scaleway PARIS-2 energy usage, but need to check their sources.

**Comment by emillon** [comment]
I just updated the README and squashed.

**Comment by patricoferris** [comment]
Brilliant, thank you!

**Pull request merged**
